"""Modify user event relationship

Revision ID: 26757bbea3d6
Revises: 3b1dd514cba9
Create Date: 2024-03-07 06:25:09.825374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26757bbea3d6'
down_revision = '3b1dd514cba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
