"""Added sender_id to the Communication model

Revision ID: 7d32635a8c74
Revises: 3868f83032da
Create Date: 2024-03-13 16:36:31.375520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d32635a8c74'
down_revision = '3868f83032da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.alter_column('datetime',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_sender_id', 'users', ['sender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sender_id', type_='foreignkey')
        batch_op.alter_column('datetime',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
