"""To Dict User model method

Revision ID: e94801d3022c
Revises: 13aa5ad8aa5f
Create Date: 2024-03-04 10:46:18.288802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94801d3022c'
down_revision = '13aa5ad8aa5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('progress')
        batch_op.drop_column('amount')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('progress')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
