"""modify event and task table

Revision ID: f39dccca543e
Revises: 3868f83032da
Create Date: 2024-03-13 16:52:50.792431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39dccca543e'
down_revision = '3868f83032da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eventTitle', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('startDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('endDate', sa.Date(), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('location')
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_date')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('amount')
        batch_op.drop_column('progress')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taskTitle', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('assignedTo', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('numParticipants', sa.String(), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('location')
        batch_op.drop_column('start_time')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('amount')
        batch_op.drop_column('progress')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('numParticipants')
        batch_op.drop_column('assignedTo')
        batch_op.drop_column('priority')
        batch_op.drop_column('taskTitle')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('endDate')
        batch_op.drop_column('startDate')
        batch_op.drop_column('eventTitle')

    # ### end Alembic commands ###
